name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List files in workspace
        run: ls -la $GITHUB_WORKSPACE

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/* ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/medusa-app

      - name: Install Node.js, PM2, and Medusa CLI on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo apt update
          sudo apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo npm install pm2 -g
          sudo npm install @medusajs/medusa-cli -g  # Install Medusa CLI globally
          EOF

      - name: Deploy Medusa on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/medusa-app
          npm install
          pm2 stop medusa || true
          pm2 start npm --name medusa -- run start  # Replace 'run start' with 'run develop' for dev mode
          EOF
